# Generated by Django 3.0.8 on 2021-01-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='phone',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
