# Generated by Django 3.0.8 on 2021-02-05 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210203_2043'),
        ('orders', '0005_auto_20210129_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Clients')),
            ],
        ),
    ]
