# Generated by Django 3.0.8 on 2021-02-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
