# Generated by Django 3.0.8 on 2021-01-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210127_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masterchef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='master_chef/%Y/%m/%d/')),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
