# Generated by Django 3.0.8 on 2021-02-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/%Y/%m/%d/')),
                ('titel', models.CharField(blank=True, max_length=400, null=True)),
                ('paragraph', models.CharField(blank=True, max_length=800, null=True)),
            ],
        ),
    ]
