# Generated by Django 3.0.8 on 2021-02-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=400)),
                ('paragraph', models.CharField(max_length=2000)),
                ('image', models.ImageField(upload_to='aboutus/%Y/%m/%d/')),
            ],
        ),
    ]
