# Generated by Django 3.0.8 on 2021-02-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_aboutusparag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='paragraph',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='titel',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
