# Generated by Django 3.0.8 on 2021-02-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210206_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='paragraph',
            field=models.CharField(blank=True, default='', max_length=800),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='titel',
            field=models.CharField(blank=True, default='', max_length=400),
            preserve_default=False,
        ),
    ]
